---
kind: pipeline
type: docker
name: lint
steps:
  - name: Lint Dockerfile
    image: hadolint/hadolint:latest-alpine
    pull: if-not-exists
    commands:
      - hadolint --version
      - hadolint Dockerfile*

---

kind: pipeline
type: docker
name: deploy

platform:
  os: linux
  arch: amd64

steps:
- name: latest  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/dhcprelay
    purge: true
    compress: true
    use_cache: true
    cache_from: "modem7/dhcprelay:latest"
    platforms: 
      - linux/amd64
      - linux/arm/v6
      - linux/arm/v7
      - linux/arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
    - cron
  cron:
    - dhcprelay_latest

depends_on:
  - lint

---

kind: pipeline
type: docker
name: monthly

platform:
  os: linux
  arch: amd64

steps:
- name: monthly  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/dhcprelay
    purge: true
    cache_from: "modem7/dhcprelay:monthly"
    platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: monthly

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
  - cron
  cron:
  - dhcprelay_monthly

---

kind: pipeline
type: docker
name: stable

platform:
  os: linux
  arch: amd64

steps:
- name: stable  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/dhcprelay
    purge: true
    cache_from: "modem7/dhcprelay:stable"
    platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: stable

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
  - cron
  cron:
  - dhcprelay_stable