kind: pipeline
type: docker
name: deploy

platform:
  os: linux
  arch: amd64

steps:
- name: latest  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/dhcprelay
    purge: true
    compress: true
    cache_from: "modem7/dhcprelay:latest"
    platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest

# trigger:
  # event:
  # - cron
  # cron:
  # - dhcprelay_latest

---

kind: pipeline
type: docker
name: monthly

platform:
  os: linux
  arch: amd64

steps:
- name: monthly  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/dhcprelay
    purge: true
    cache_from: "modem7/dhcprelay:latest"
    platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: monthly

# trigger:
  # event:
  # - cron
  # cron:
  # - dhcprelay_monthly

---

kind: pipeline
type: docker
name: stable

platform:
  os: linux
  arch: amd64

steps:
- name: stable  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/dhcprelay
    purge: true
    cache_from: "modem7/dhcprelay:latest"
    platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: stable

# trigger:
  # event:
  # - cron
  # cron:
  # - dhcprelay_stable