 #############
 ##DHCPRelay##
 #############

 #DHCPRelay - DHCP Relay between host network and PiHole bridge
services:
  dhcprelay:
    image: modem7/dhcprelay:latest
    container_name: DHCPRelay
    environment:
      DHCRELAY_DOWN_INTERFACE: eno1
      DHCRELAY_UP_INTERFACE: br_pihole #https://fedoramagazine.org/build-network-bridge-fedora/
      DHCRELAY_SERVERS: 172.33.0.100
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
      - NET_BIND_SERVICE
    network_mode: host
    restart: always
    mem_limit: 20m
    mem_reservation: 5m
